services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./poetry.lock:/app/poetry.lock
    environment:
      - ENVIRONMENT=development
    env_file:
      - path: .env
        required: false
