sonar.projectKey=dockyard2sail-py
sonar.projectName=dockyard2sail-py
sonar.host.url=http://localhost:9000
sonar.sources=src
sonar.tests=tests
sonar.language=py
sonar.exclusions=**/__pycache__/**,**/.venv/**
sonar.python.coverage.reportPaths=coverage.xml
